import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { workspaceLayout } from '../../workspace/paths.js';

export class ReportGenerator {
  private static instance: ReportGenerator;
  private reportDir: string;

  private constructor() {
    this.reportDir = path.join(workspaceLayout().outputs, 'swarm-reports');
  }

  static getInstance(): ReportGenerator {
    if (!ReportGenerator.instance) {
      ReportGenerator.instance = new ReportGenerator();
    }
    return ReportGenerator.instance;
  }

  async ensureDir() {
    if (!existsSync(this.reportDir)) {
      await mkdir(this.reportDir, { recursive: true });
    }
  }

  async saveReport(agentName: string, content: string, status: 'doing' | 'done' | 'planning') {
    await this.ensureDir();
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${agentName.toLowerCase()}-${status}-${timestamp}.md`;
    const filePath = path.join(this.reportDir, filename);

    const formattedContent = [
      `# Swarm Status Report: ${agentName}`,
      `**Status:** ${status.toUpperCase()}`,
      `**Timestamp:** ${new Date().toLocaleString()}`,
      `---`,
      content,
      `---`,
      `*Generated by ZilMate Swarm Protocol*`
    ].join('\n\n');

    await writeFile(filePath, formattedContent, 'utf8');

    // Also update a "current-status.md" for easy tracking
    const currentPath = path.join(this.reportDir, `${agentName.toLowerCase()}-current.md`);
    await writeFile(currentPath, formattedContent, 'utf8');

    return filePath;
  }
}
